=== NastyaViter/ProductsStore/src/main/resources/xml-parser/catalogSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalog">
        <xs:complexType >
            <xs:sequence>
                <xs:element name="product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name = "name" type="xs:string">
                            </xs:element>
                            <xs:element name = "attributes">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "price" type="xs:decimal" nillable="false"></xs:element>
                                        <xs:element name = "summary" type="xs:string"></xs:element>
                                        <xs:element name = "operatingSystem" type="xs:string" nillable="false"></xs:element>
                                        <xs:element name = "processorSpeedGHz" type="xs:decimal"></xs:element>
                                        <xs:element name = "capacityGB" type="xs:integer"></xs:element>
                                        <xs:element name = "displayInch" type="xs:decimal"></xs:element>
                                        <xs:element name = "heightMM" type="xs:decimal"></xs:element>
                                        <xs:element name = "widthMM" type="xs:decimal"></xs:element>
                                        <xs:element name = "depthMM" type="xs:decimal"></xs:element>
                                        <xs:element name = "weightGrams" type="xs:decimal"></xs:element>
                                        <xs:element name = "cameraMP" type="xs:decimal"></xs:element>
                                        <xs:element name = "batteryHours" type="xs:decimal"></xs:element>
                                        <xs:element name = "simCard" type="xs:string"></xs:element>
                                        <xs:element name = "quantity" type="xs:integer"></xs:element>
                                        <xs:element name = "imageURL" type="xs:anyURI"></xs:element>
                                        <xs:element name = "fabricator" type="xs:string"></xs:element>
                                     </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NastyaViter/ProductsStore/src/main/resources/xml-parser/generatedCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogSchema.xsd">
  <telephone>
    <name>iPhone61S</name>
    <attributes/>
  </telephone>
  <telephone>
    <name>Galaxy S10 Edge</name>
    <attributes/>
  </telephone>
  <telephone>
    <name>iPhone6S</name>
    <attributes>
      <price>549.0</price>
      <summary>IPhone 6s embody Apples continuing environmental progress</summary>
      <operatingSystem>iOS 10</operatingSystem>
      <processorSpeedGHz>1.8</processorSpeedGHz>
      <capacityGB>32</capacityGB>
      <displayInch>4.7</displayInch>
      <heightMM>138.3</heightMM>
      <widthMM>67.1</widthMM>
      <depthMM>7.1</depthMM>
      <weightGrams>143</weightGrams>
      <cameraMP>12</cameraMP>
      <batteryHours>14</batteryHours>
      <simCard>Nano-SIM</simCard>
      <fabricator>Apple</fabricator>
      <imageURL>URL</imageURL>
    </attributes>
  </telephone>
  <telephone>
    <name>iPhone5S</name>
    <attributes>
      <price>258.0</price>
      <summary>Apple iPhone 5s smartphone was launched in September 2013</summary>
      <operatingSystem>iOS 7</operatingSystem>
      <processorSpeedGHz>1.3</processorSpeedGHz>
      <capacityGB>16</capacityGB>
      <displayInch>4.0</displayInch>
      <heightMM>123.8</heightMM>
      <widthMM>58.6</widthMM>
      <depthMM>7.6</depthMM>
      <weightGrams>112</weightGrams>
      <cameraMP>8</cameraMP>
      <batteryHours>10</batteryHours>
      <simCard>Nano-SIM</simCard>
      <fabricator>Apple</fabricator>
      <imageURL>URL</imageURL>
    </attributes>
  </telephone>
  <telephone>
    <name>Galaxy S7 Edge</name>
    <attributes>
      <price>769.99</price>
      <summary>Samsung has created a beautiful phone with water resistance and fast loading</summary>
      <operatingSystem>Android 6.0</operatingSystem>
      <processorSpeedGHz>2.15</processorSpeedGHz>
      <capacityGB>32</capacityGB>
      <displayInch>5.5</displayInch>
      <heightMM>150.9</heightMM>
      <widthMM>72.6</widthMM>
      <depthMM>7.7</depthMM>
      <weightGrams>157</weightGrams>
      <cameraMP>12</cameraMP>
      <batteryHours>13</batteryHours>
      <simCard>Nano-SIM</simCard>
      <fabricator>Samsung</fabricator>
      <imageURL>URL</imageURL>
    </attributes>
  </telephone>
  <telephone>
    <name>iPhone88S</name>
    <attributes/>
  </telephone>
  <tablet>
    <name>iPad mini 44</name>
    <attributes/>
  </tablet>
  <tablet>
    <name>iPad Air 2</name>
    <attributes>
      <price>399</price>
      <summary>iPad Air 2</summary>
      <operatingSystem>iOS</operatingSystem>
      <processorSpeedGHz>1.5</processorSpeedGHz>
      <capacityGB>32</capacityGB>
      <displayInch>9.7</displayInch>
      <heightMM>240</heightMM>
      <widthMM>169.5</widthMM>
      <depthMM>6.1</depthMM>
      <weightGrams>437</weightGrams>
      <cameraMP>8</cameraMP>
      <batteryHours>10</batteryHours>
      <simCard>Nano-SIM</simCard>
      <fabricator>Apple</fabricator>
      <imageURL>URL</imageURL>
    </attributes>
  </tablet>
  <tablet>
    <name>iPad mini 4</name>
    <attributes>
      <price>399</price>
      <operatingSystem>iOS</operatingSystem>
      <processorSpeedGHz>1.5</processorSpeedGHz>
      <capacityGB>32</capacityGB>
      <displayInch>7.9</displayInch>
      <heightMM>203.2</heightMM>
      <widthMM>134.8</widthMM>
      <depthMM>6.1</depthMM>
      <weightGrams>298.8</weightGrams>
      <cameraMP>8</cameraMP>
      <batteryHours>10</batteryHours>
      <simCard>Nano-SIM</simCard>
      <fabricator>Apple</fabricator>
      <imageURL>URL</imageURL>
    </attributes>
  </tablet>
  <tablet>
    <name>iPad Air 42</name>
    <attributes/>
  </tablet>
</catalog>

=== NastyaViter/ProductsStore/src/main/resources/xml-parser/catalogToAdd.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogSchema.xsd">
    
    <tablet>
        <name>iPad mini 44</name>
        <attributes>
            <price>399</price>
            <summary>p</summary>
            <operatingSystem>iOS</operatingSystem>
            <processorSpeedGHz>1.5</processorSpeedGHz>
            <capacityGB>32</capacityGB>
            <displayInch>7.9</displayInch>
            <heightMM>203.2</heightMM>
            <widthMM>134.8</widthMM>
            <depthMM>6.1</depthMM>
            <weightGrams>298.8</weightGrams>
            <cameraMP>8</cameraMP>
            <batteryHours>10</batteryHours>
            <simCard>Nano-SIM</simCard>
            <fabricator>Apple</fabricator>
            <imageURL>URL</imageURL>
        </attributes>
    </tablet>

</catalog>
